apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: <UPDATE WITH KV NAME>
    - name: spnTenantId
      value: <UPDATE WITH TENANT ID>
    - name: spnClientId
      value: <UPDATE WITH SP ID>
    - name: spnCertificateFile
      value: <UPDATE WITH PATH TO REPO>secrets-dapr/dapr-secret-sync/local-simple/simplekv02.pfx
