apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: simplekvdapr0002
    - name: spnTenantId
      value: 61c5e8da-0049-4945-91fa-bd80a63f2909
    - name: spnClientId
      value: cc58f2df-20f3-4099-b16b-9872d1638dad
    - name: spnCertificateFile
      value: /Users/juanburckhardt/repos/wallmart/secrets-dapr/dapr-secret-sync/local-simple/simplekv02.pfx
