apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: mysecret2
  namespace: default
spec:
  vault:
    name: simplekvdapr0001 # name of key vault
    object:
      name: mysecret2 # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: mysecret2 # kubernetes secret name
      dataKey: secret-value # key to store object value in kubernetes secret
