apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: mysecret
  namespace: default
spec:
  vault:
    name: <UPDATE WITH KV NAME> # name of key vault
    object:
      name: mysecret # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: mysecret # kubernetes secret name
      dataKey: mysecret # key to store object value in kubernetes secret
